- name: create user
  hosts: all
  become: yes

  tasks:
    - name: create kube user
      user: name=kube append=yes state=present createhome=yes shell=/bin/bash

    - name: grant access to kube
      lineinfile:
        dest: /etc/sudoers
        line: 'kube ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: kube user key
      authorized_key: user=kube key="{{item}}"
      with_file:
       - ./id_rsa.pub
